import Head from "next/head";

export default function Header(props) {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="JarujaruDB Generated by a fan of Jarujaru!!!!!!" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}