import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Footer from './components/base/Footer/Footer';
import Layout from './components/layout';

import DataList from './components/products/FeaturedList';
import TopCategories from './components/TopPage/TopPage/TopCategories';

export async function getServerSideProps() {
  //const response = await fetch('http://localhost:3000/api/moviesdb');//local
  const response = await fetch('https://jarujarudb.vercel.app/api/moviesdb/kantoujin');//deployment
  const data = await response.json();

  return { props: { data } };
}

export default function Kantoujin({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ジャルジャルDB</title>
        <meta name="description" content="Generated by a fan of Jarujaru" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Layout header='ジャルジャルDB'>
          
          <br/>
            
            <TopCategories/>
          </Layout>
        </div>
      </main>
      <Footer/>
    </div>
  )
}
