//import MuiPagination from '@mui/lab/Pagination';
import { Grid, Pagination as MuiPagination } from '@mui/material';
import { withStyles } from '@mui/styles';
import Head from 'next/head';
import {useEffect, useState} from 'react';

import styles from '../styles/Home.module.css';
import Footer from './components/base/Footer/Footer';
import Layout from './components/layout';
import DatasList from './components/products/DatasList';
import TopCategories from './components/TopPage/TopPage/TopCategories';

export default function Top() {
  const [page, setPage] = useState(1);//ページ番号
  const [count, setCount] = useState();//総ページ数
  const [bookList, setBookList] = useState([]);//取得した本のリスト

  useEffect(async () => {
    setBookListAPI(page);
    //console.log('page:\n',page)
  }, []);

  //ページ番号をクリックしたときの処理
  const clickPage = (e, page) => {
    setPage(page);
    setBookListAPI(page);
  }

  //取得データのセットと総データ件数をセットする
  const setBookListAPI = async(page) => {
    const response = await fetch('https://jarujarudb.vercel.app/api/moviesdb/top');//deployment
    //const response = await fetch(`http://localhost:3000/api/moviesdb/top?page=${page}`);
    const data = await response.json();

    console.log('data:\n',data)

    setBookList(data.rows);//.rows);//取得データ
    setCount(data.count);//総データ件数
  }

  const Pagination = withStyles({
    root: {
      display: 'inline-block',//中央寄せのためインラインブロックに変更
    },
  }) (MuiPagination);

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>ジャルジャルDB</title>
        <meta name="description" content="Generated by a fan of Jarujaru" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Layout header='ジャルジャルDB'>
          <br/>
            
      <Grid container direction="column">
        <Grid container className={styles.datalist}>
                
          {bookList.length > 0 && (
            bookList.map((data) => {
              const beforestr = data.url
              const regex = /(?<=v=)(.*)/
              const result = beforestr.match(regex);
              const urlv = result[0]
              
              let gotolink = 'https://www.youtube.com/watch?v='+urlv
              const viewstext = ' 回視聴'
              return (
                <>
                <Grid item xs={12} sm={3} key={data.no}>
                  <DatasList
                    url={data.url} title={data.title} views={data.views} thumbnail={data.thumbnail}
                    created_at={data.created_at}
                    //custom text _etc.
                    gotolink={gotolink} viewstext={viewstext}
                  /></Grid>
                </>
                )}))}
                
                </Grid>
                </Grid>
      
      <div style={{marginTop: "50px", textAlign: "center"}}>
        <Pagination
          count={count}//総ページ数
          color="primary"
          onChange={clickPage}//変更されたときに走る関数。第2引数にページ番号が入る
          page={page}
        />
      </div>
      <br/>

      <TopCategories/>
          </Layout>
        </div>
      </main>
      <Footer/>
    </div>
    </>
  );
}